# Generated by Django 4.2.27 on 2026-01-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_challenge_updates", models.BooleanField(default=True)),
                ("email_team_updates", models.BooleanField(default=True)),
                ("email_reward_updates", models.BooleanField(default=True)),
                ("email_weekly_digest", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_challenge_updates", models.BooleanField(default=True)),
                ("push_team_updates", models.BooleanField(default=True)),
                ("push_reward_updates", models.BooleanField(default=True)),
                ("in_app_challenge_updates", models.BooleanField(default=True)),
                ("in_app_team_updates", models.BooleanField(default=True)),
                ("in_app_reward_updates", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("challenge_invite", "Challenge Invitation"),
                            ("challenge_reminder", "Challenge Reminder"),
                            ("challenge_completed", "Challenge Completed"),
                            ("duel_request", "Duel Request"),
                            ("duel_accepted", "Duel Accepted"),
                            ("duel_declined", "Duel Declined"),
                            ("duel_won", "Duel Won"),
                            ("duel_lost", "Duel Lost"),
                            ("proof_approved", "Proof Approved"),
                            ("proof_rejected", "Proof Rejected"),
                            ("proof_review_request", "Proof Review Request"),
                            ("team_invite", "Team Invitation"),
                            ("team_joined", "Team Member Joined"),
                            ("team_left", "Team Member Left"),
                            ("team_nudge", "Team Nudge"),
                            ("badge_earned", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("streak_milestone", "Streak Milestone"),
                            ("streak_warning", "Streak At Risk"),
                            ("streak_broken", "Streak Broken"),
                            ("system", "System Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("action_label", models.CharField(blank=True, max_length=50)),
                ("related_challenge_id", models.IntegerField(blank=True, null=True)),
                ("related_team_id", models.IntegerField(blank=True, null=True)),
                ("related_user_id", models.IntegerField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"], name="notificatio_user_id_f77590_idx"
                    ),
                ],
            },
        ),
    ]
