# Generated by Django 5.0.14 on 2026-01-16 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('global', 'Global Challenge'), ('duel', 'One-on-One Duel'), ('team', 'Team Challenge'), ('community', 'Community Challenge')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('goal', models.CharField(help_text='What participants need to achieve', max_length=255)),
                ('target_value', models.IntegerField(help_text='Target number/value to achieve', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('reward_points', models.IntegerField(default=0)),
                ('winner_reward_multiplier', models.FloatField(default=1.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_participants',
                'ordering': ['-current_progress'],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='participated_challenges', through='challenges.ChallengeParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stake_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.OneToOneField(limit_choices_to={'challenge_type': 'duel'}, on_delete=django.db.models.deletion.CASCADE, related_name='duel', to='challenges.challenge')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_duels', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_duels', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_duels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', '-start_date'], name='challenges_status_9bf449_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenge_type'], name='challenges_challen_b892f4_idx'),
        ),
    ]
