# Generated by Django 4.2.27 on 2026-01-16 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=1, help_text='Numeric value of this contribution', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Optional note about this contribution')),
                ('status', models.CharField(choices=[('pending', 'Pending Proof'), ('awaiting_review', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('logged_at', models.DateTimeField(help_text='When the activity was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contributions',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('SELF', 'Self Confirmation'), ('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('PEER', 'Peer Verification'), ('SENSOR', 'Sensor Data')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proofs/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='proofs/videos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='proofs/documents/')),
                ('sensor_data', models.JSONField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proofs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proof_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='min_peer_approvals',
            field=models.PositiveIntegerField(default=1, help_text='Minimum peer approvals needed for PEER proof'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='proof_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours after contribution to submit proof'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='required_proof_types',
            field=models.JSONField(blank=True, default=list, help_text='Required proof types for completion (list of SELF, PHOTO, VIDEO, DOCUMENT, PEER, SENSOR)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='teams.team'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement (e.g., km, reps)', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team Only'), ('invite', 'Invite Only'), ('public', 'Public')], default='private', help_text='Who can see this challenge', max_length=20),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='last_contribution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='streak_best',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='streak_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('todo', 'One-time Todo'), ('streak', 'Habit/Streak'), ('program', 'Program (Multi-day)'), ('quantified', 'Quantified Goal'), ('team', 'Team Challenge'), ('duel', 'One-on-One Duel'), ('team_vs_team', 'Team vs Team'), ('community', 'Community Challenge'), ('global', 'Global Challenge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='current_progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregated progress value', max_digits=12),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['visibility'], name='challenges_visibil_028d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['creator', '-created_at'], name='challenges_creator_fa353d_idx'),
        ),
        migrations.AddField(
            model_name='proofreview',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='challenges.proof'),
        ),
        migrations.AddField(
            model_name='proofreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proof',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='challenges.contribution'),
        ),
        migrations.AddField(
            model_name='proof',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='challenges.challengeparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='proofreview',
            unique_together={('proof', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['contribution', 'proof_type'], name='proofs_contrib_b4b912_idx'),
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['status'], name='proofs_status_9d6c96_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['participation', '-logged_at'], name='contributio_partici_be8797_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='contributio_status_b92c24_idx'),
        ),
    ]
