# Generated by Django 4.2.27 on 2026-01-16 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0002_contribution_proof_proofreview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Audio file (WebM, MP3, WAV, M4A)", upload_to="voice_memos/%Y/%m/"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Duration of the audio in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Transcription"),
                            ("transcribing", "Transcribing"),
                            ("transcribed", "Transcribed"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("challenge_created", "Challenge Created"),
                            ("task_created", "Task Created"),
                            ("dismissed", "Dismissed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "transcription",
                    models.TextField(blank=True, help_text="Whisper API transcription result"),
                ),
                (
                    "transcription_confidence",
                    models.FloatField(
                        blank=True, help_text="Confidence score from transcription", null=True
                    ),
                ),
                (
                    "language_detected",
                    models.CharField(
                        blank=True,
                        help_text="Detected language code (e.g., 'de', 'en')",
                        max_length=10,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="AI-parsed challenge/task data"
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True, help_text="AI confidence in the parsed result", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("transcribed_at", models.DateTimeField(blank=True, null=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_memos",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_memos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_memos",
                "ordering": ["-created_at"],
            },
        ),
    ]
