# Generated by Django 4.2.27 on 2026-01-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(db_index=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of related challenge or habit', null=True)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('best_count', models.PositiveIntegerField(default=0)),
                ('grace_used', models.PositiveIntegerField(default=0, help_text='Number of grace days used')),
                ('max_grace', models.PositiveIntegerField(default=1, help_text='Maximum grace days allowed')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streaks',
                'indexes': [models.Index(fields=['user', 'streak_type'], name='streaks_user_id_9d38b8_idx'), models.Index(fields=['-current_count'], name='streaks_current_ad4485_idx')],
                'unique_together': {('user', 'streak_type', 'reference_id')},
            },
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_amount', models.IntegerField(default=0)),
                ('coins_amount', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('contribution_approved', 'Contribution Approved'), ('challenge_completed', 'Challenge Completed'), ('challenge_won', 'Challenge Won'), ('streak_milestone', 'Streak Milestone'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('team_bonus', 'Team Bonus'), ('daily_login', 'Daily Login'), ('referral', 'Referral Bonus'), ('admin_grant', 'Admin Grant')], max_length=30)),
                ('reason_detail', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, help_text="Model name of source (e.g., 'Contribution', 'Challenge')", max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='ID of the source object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(blank=True, limit_choices_to={'reward_type': 'badge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reward_even_user_id_1a4ced_idx'), models.Index(fields=['reason'], name='reward_even_reason_530208_idx'), models.Index(fields=['source_type', 'source_id'], name='reward_even_source__82c5ac_idx')],
            },
        ),
    ]
