# Generated by Django 4.2.27 on 2026-01-16 22:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rewards", "0002_streak_rewardevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("signup_bonus", models.IntegerField(default=100)),
                ("referral_bonus", models.IntegerField(default=25)),
                ("cost_todo", models.IntegerField(default=5)),
                ("cost_streak", models.IntegerField(default=10)),
                ("cost_quantified", models.IntegerField(default=10)),
                ("cost_duel", models.IntegerField(default=15)),
                ("cost_team", models.IntegerField(default=20)),
                ("cost_community", models.IntegerField(default=50)),
                ("cost_photo_proof", models.IntegerField(default=5)),
                ("cost_video_proof", models.IntegerField(default=10)),
                ("cost_peer_review", models.IntegerField(default=3)),
                ("reward_task_complete", models.IntegerField(default=3)),
                (
                    "reward_challenge_complete_percent",
                    models.IntegerField(
                        default=80, help_text="Percent of creation cost returned on completion"
                    ),
                ),
                ("reward_streak_7", models.IntegerField(default=10)),
                ("reward_streak_30", models.IntegerField(default=50)),
                ("reward_streak_100", models.IntegerField(default=200)),
                ("reward_peer_review", models.IntegerField(default=1)),
                ("reward_badge_common", models.IntegerField(default=5)),
                ("reward_badge_rare", models.IntegerField(default=15)),
                ("reward_badge_epic", models.IntegerField(default=50)),
                ("total_credits_minted", models.BigIntegerField(default=0)),
                ("total_credits_burned", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credit Configuration",
                "verbose_name_plural": "Credit Configuration",
                "db_table": "credit_config",
            },
        ),
        migrations.CreateModel(
            name="CreditWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current credit balance",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lifetime_earned",
                    models.IntegerField(default=0, help_text="Total credits earned over lifetime"),
                ),
                (
                    "lifetime_spent",
                    models.IntegerField(default=0, help_text="Total credits spent over lifetime"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_wallets",
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("signup_bonus", "Signup Bonus"),
                            ("challenge_complete", "Challenge Completed"),
                            ("task_complete", "Task Completed"),
                            ("streak_milestone", "Streak Milestone"),
                            ("duel_won", "Duel Won"),
                            ("peer_review", "Peer Review"),
                            ("badge_earned", "Badge Earned"),
                            ("referral_bonus", "Referral Bonus"),
                            ("purchase", "Credit Purchase"),
                            ("admin_grant", "Admin Grant"),
                            ("refund", "Refund"),
                            ("challenge_create", "Challenge Created"),
                            ("task_create", "Task Created"),
                            ("duel_stake", "Duel Stake"),
                            ("feature_unlock", "Feature Unlock"),
                            ("transfer_out", "Transfer Out"),
                            ("expiry", "Credit Expiry"),
                            ("admin_deduct", "Admin Deduction"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Positive for earning, negative for spending"),
                ),
                ("balance_after", models.IntegerField(help_text="Balance after this transaction")),
                ("description", models.CharField(blank=True, max_length=500)),
                ("related_content_type", models.CharField(blank=True, max_length=100, null=True)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="rewards.creditwallet",
                    ),
                ),
            ],
            options={
                "db_table": "credit_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"], name="credit_tran_wallet__20b383_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"], name="credit_tran_transac_0eee54_idx"
                    ),
                ],
            },
        ),
    ]
