# Generated by Django 4.2.27 on 2026-01-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "debug_mode_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether debug feedback is enabled globally"
                    ),
                ),
                (
                    "auto_implement",
                    models.BooleanField(
                        default=False, help_text="Automatically implement AI suggestions"
                    ),
                ),
                (
                    "auto_commit",
                    models.BooleanField(
                        default=False, help_text="Automatically commit implemented changes"
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(
                        default=True, help_text="Require admin approval before implementing"
                    ),
                ),
                (
                    "feedback_cost",
                    models.IntegerField(
                        default=1, help_text="Credits cost per feedback submission"
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="AI model to use for analysis",
                        max_length=50,
                    ),
                ),
                (
                    "unlimited_credit_usernames",
                    models.JSONField(
                        default=list,
                        help_text="Usernames that have unlimited credits (e.g., ['crorry'])",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debug Configuration",
                "verbose_name_plural": "Debug Configuration",
            },
        ),
        migrations.CreateModel(
            name="DebugFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "text_input",
                    models.TextField(blank=True, help_text="Text description of the feedback"),
                ),
                (
                    "voice_memo",
                    models.FileField(
                        blank=True,
                        help_text="Voice memo recording",
                        null=True,
                        upload_to="debug_feedback/voice/",
                    ),
                ),
                (
                    "voice_transcription",
                    models.TextField(blank=True, help_text="Transcription of voice memo"),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("ui_change", "UI/Design Change"),
                            ("improvement", "General Improvement"),
                            ("other", "Other"),
                        ],
                        default="improvement",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True, default=dict, help_text="AI analysis of the feedback"
                    ),
                ),
                (
                    "ai_suggested_changes",
                    models.JSONField(
                        blank=True, default=list, help_text="AI suggested file changes"
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(default=0.0, help_text="AI confidence in analysis (0-1)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Analysis"),
                            ("analyzing", "AI Analyzing"),
                            ("analyzed", "Analysis Complete"),
                            ("implementing", "Implementing"),
                            ("implemented", "Implemented"),
                            ("committed", "Committed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "affected_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of files that were/will be changed",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        blank=True, help_text="Git commit hash if committed", max_length=40
                    ),
                ),
                ("commit_message", models.TextField(blank=True, help_text="Git commit message")),
                (
                    "credits_cost",
                    models.IntegerField(default=1, help_text="Credits charged for this feedback"),
                ),
                (
                    "credits_charged",
                    models.BooleanField(
                        default=False, help_text="Whether credits have been charged"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, help_text="Page URL where feedback was submitted"),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="debug_feedback/screenshots/"
                    ),
                ),
                (
                    "browser_info",
                    models.JSONField(blank=True, default=dict, help_text="Browser/device info"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debug_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debug Feedback",
                "verbose_name_plural": "Debug Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebugFeedbackComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="debug_feedback.debugfeedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
