# Generated by Django 4.2.27 on 2026-01-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.login', 'User Login'), ('auth.logout', 'User Logout'), ('auth.login_failed', 'Login Failed'), ('auth.password_reset_request', 'Password Reset Request'), ('auth.password_reset_complete', 'Password Reset Complete'), ('auth.password_change', 'Password Change'), ('auth.mfa_enable', 'MFA Enabled'), ('auth.mfa_disable', 'MFA Disabled'), ('user.create', 'User Created'), ('user.update', 'User Updated'), ('user.delete', 'User Deleted'), ('user.deactivate', 'User Deactivated'), ('team.create', 'Team Created'), ('team.update', 'Team Updated'), ('team.delete', 'Team Deleted'), ('team.member_add', 'Member Added to Team'), ('team.member_remove', 'Member Removed from Team'), ('team.role_change', 'Member Role Changed'), ('challenge.create', 'Challenge Created'), ('challenge.update', 'Challenge Updated'), ('challenge.delete', 'Challenge Deleted'), ('challenge.visibility_change', 'Challenge Visibility Changed'), ('challenge.join', 'Joined Challenge'), ('challenge.leave', 'Left Challenge'), ('proof.submit', 'Proof Submitted'), ('proof.approve', 'Proof Approved'), ('proof.reject', 'Proof Rejected'), ('proof.flag', 'Proof Flagged'), ('admin.user_suspend', 'User Suspended by Admin'), ('admin.content_remove', 'Content Removed by Admin')], db_index=True, max_length=50)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, help_text='SHA256 hash of IP for privacy', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
    ]
